### ISSUE TITLE
Maximum resolution not being downloaded.

### ISSUE THREAD

**Issue by 0hmy** [gedsic/tumbdl#10]
I have noticed that even though there's a script for selecting the highest resolution available for the image, for a big part of them there's a higher resolution available not being downloaded (I've verified it by taking the link of some images downloaded with the "_500" or less resolution and manually changing the link to "_1280" and getting higher-res images). Since there's a "_1280" version of every images, even if the source picture is smaller and it's the same resolution as a "_500" version, an easy workaround for this issue would be to always force download the "_1280" version of an image, so the script will always get the highest resolution available.

**Comment by gedsic** [comment]
Thanks for the info. Please try the newest version after the merge with #11.

I don't want to always download the _1280 version because I don't know if that breaks some time. Twitter already seems to store different sizes on different servers sometimes.

I'm currently rewriting the whole script to rely on curl. Images alread work and it includes a more robust maximum resolution detection. Will update this after commit.
